### ISSUE TITLE
Error: The SDK configuration is invalid

### ISSUE THREAD

**Issue by rmtuckerphx** [voxalyze/jovo-plugin#1]
Just added Voxalyze Jovo Plugin to my JavaScript project that uses Jovo:

```
Jovo CLI Version: 3.0.7

Jovo packages of current project:
  jovo-analytics-dashbot: 3.0.14
  jovo-cms-i18next: 3.0.12
  jovo-community-plugin-sentry: 1.2.1
  jovo-core: 3.0.12
  jovo-db-dynamodb: 3.0.12
  jovo-db-filedb: 3.0.12
  jovo-framework: 3.0.12
  jovo-platform-alexa: 3.0.12
  jovo-plugin-debugger: 3.0.12
  jovo-plugin-speechmarkdown: 1.3.0
```

I followed the instructions:

```
$ npm install -S @voxalyze/jovo-plugin
```

```
// app.js
const { Voxalyze } = require('@voxalyze/jovo-plugin');

app.use(
  new Alexa(),
  new JovoDebugger(),
  new SentryPlugin(),
  new SpeechMarkdown(),
  new FileDb(),
  new DynamoDb(),
  new DashbotAlexa(),
  new Voxalyze(),
);
```

```
// config.js
  plugin: {
    Voxalyze: {
      apiKey: 'xxx', // or process.env.VOXALYZE_KEY
    },
...
```

But when I run the app using `jovo run` then I get the error:
Error: The SDK configuration is invalid

**Comment by marianzange** [comment]
Hi Mark,

Sorry for the inconvenience and thanks for reporting this! The issue was related to the way the plugin is packaged for release. This led to Jovo being unable to infer the plugin name from the class name. It should work now as expected once you upgrade to [version 0.0.3](https://www.npmjs.com/package/@voxalyze/jovo-plugin)

Please note, that the **Jovo Debugger is currently not supported** from our side. We're working on a solution, but at the moment Skill IDs need to be globally unique in our system. 

From what I've seen, the Jovo Debugger sets the same dummy skill ID for everyone, so our API will reject it. Nonetheless, when you run the debugger and send a launch request through it, you should see `[VoxalyzeSDK][ERROR] HTTP dispatch failed: 403 Forbidden`. This indicates that everything is working besides our API rejecting the dummy skill ID.
